using Godot;

namespace AssetTools.UCWorld.Poly;

/// <summary>
/// A 4 point quad used as a Strip. This is used for map floors.
/// In original code this is generated by calling draw_i_prim or DrawIndPrimMM with certain parameters
/// 
/// Note that while this looks like QuadPoly, the Indexes are different.
/// </summary>
public class FloorPoly : BasePoly, IPoly
{
	public FloorPoly(MapVertex vertex1, MapVertex vertex2, MapVertex vertex3, MapVertex vertex4, int texture = -1) {
		this.MapVertices = [vertex1, vertex2, vertex3, vertex4];
		this.TexturePage = texture;
	}

	public int[] GetIndices() => [0, 1, 2, 1, 3, 2];

	public Vector3 GetNormal() => Vector3.Up;
}
