namespace AssetTools.UCWorld.Poly;

/// <summary>
/// A common Quad.
/// In original code this is generated by POLY_add_quad
/// </summary>
public class QuadPoly : IPoly
{
	private readonly MapVertex[] MapVertices;

	private readonly int TexturePage;

	public QuadPoly(MapVertex vertex1, MapVertex vertex2, MapVertex vertex3, MapVertex vertex4, int texture = -1) {
		this.MapVertices = [vertex1, vertex2, vertex3, vertex4];
		this.TexturePage = texture;
	}

	/**
	 *  3 - 2
	 *  | / |
	 *  1 - 0
	 */
	public int[] GetIndices() => [0, 2, 1, 1, 2, 3];
	public int GetTexturePage() => this.TexturePage;
	public MapVertex[] GetVertices() => this.MapVertices;
}
