namespace AssetTools.UCWorld.Poly;

/// <summary>
/// A common Triangle.
/// In original code this is generated by calling POLY_add_triangle
/// </summary>
public class TrianglePoly : IPoly
{
	private readonly MapVertex[] MapVertices;

	private readonly int TexturePage;

	public TrianglePoly(MapVertex vertex1, MapVertex vertex2, MapVertex vertex3, int texture = -1) {
		this.MapVertices = [vertex1, vertex2, vertex3];
		this.TexturePage = texture;
	}

	public int[] GetIndices() => [0, 1, 2];
	public int GetTexturePage() => this.TexturePage;
	public MapVertex[] GetVertices() => this.MapVertices;
}
