using Godot;

namespace AssetTools.UCWorld.Poly;

/// <summary>
/// A common Triangle.
/// In original code this is generated by calling POLY_add_triangle
/// </summary>
public class TrianglePoly : BasePoly, IPoly
{
	public TrianglePoly(MapVertex vertex1, MapVertex vertex2, MapVertex vertex3, int texture = -1) {
		this.MapVertices = [vertex1, vertex2, vertex3];
		this.TexturePage = texture;
	}

	public int[] GetIndices() => [0, 1, 2];
	public Vector3 GetNormal() => Vector3.Back; // @TODO: This was a guess
}
